### ISSUE TITLE
Aferir Conhecimento da Equipe

### ISSUE THREAD

**Issue by Lcunha** [fga-eps-mds/2018.2-RolesFGA#5]
Aferir o conhecimento da equipe através do preenchimento do quadro de conhecimento.

[Quadro de Conhecimento](https://docs.google.com/spreadsheets/d/1mXsXZEdywSWpf9S7JXJh2vwu1GwzwL2qezD4116MHQo/edit?usp=sharing)

**Comment by gleal17** [comment]
Quadro de conhecimento vai seguir algum template?

**Comment by gleal17** [comment]
Quadro de conhecimento vai seguir algum template?

**Comment by Lcunha** [comment]
Template Atualizado!!

**Comment by gleal17** [comment]
Corrigida as informações solicitadas.

**Comment by iagoomr** [comment]
Tem um quadro ainda marcado com "?" do Henrique Martins, acho que ele esqueceu desse

**Comment by VictorRodriguesS0** [comment]
Atualizado

**Comment by Henrike100** [comment]
Atualizei minha parte.
